Initial OpenBSD build support
FyshOS/fin pull request #17
Opened 2022-09-05 18:58 UTC by vazub

Requires 'pkg_add openpam'.

Display manager starts fine in embedded session with Xephyr, but doesn't authenticate yet - logs "pam_start: system error" and needs further investigation to make port work.

2022-09-05 21:55 UTC, andydotxyz requested changes
If this requires additional setup then the README and/or Makefile should be updated too.

2022-09-05 21:55 UTC, andydotxyz commented on pam.go
> +#cgo openbsd LDFLAGS: -L/usr/local//lib
The double slash doesn't look right

2022-09-06 08:48 UTC, vazub commented
Added text to README to address OpenBSD topic.

2022-09-06 11:21 UTC, andydotxyz requested changes
Thanks for the changes, but you have committed merge conflicts as far as I can see

2022-09-06 11:31 UTC, vazub commented
> merge conflicts as far as I can see

I had git acting up for some reason, but there was no real conflict in the end, if you look at the actual changes @andydotxyz

2022-09-06 11:38 UTC, andydotxyz commented
> > merge conflicts as far as I can see
> 
> I had git acting up for some reason, but there was no real conflict in the end, if you look at the actual changes @andydotxyz If that is still a bother, I can abandon this PR and create a fresh one, with all the changes in one go.

Look at the diff, there are two instances of `<<<<<<< HEAD` - I am pretty sure this is not what you intended.

2022-09-06 12:00 UTC, closed without merging